version: 0.2
env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Build started on `date`

  pre_build:
    commands:
      - echo "Pre-build steps..."
      - npm i parcel
      - npx update-browserslist-db@latest  # Update caniuse-lite

  build:
    commands:
      - cd demo
      - npm install
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - pwd && ls -l
      - aws s3 cp --recursive --acl public-read ./dist s3://webreactdemo/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./dist/index.html s3://webreactdemo/

artifacts:
  files:
    - 'dist/**/*'