version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Build started on `date`

  pre_build:
    commands:
      - echo "Pre-build steps..."

  build:
    commands:
      - cd demo
      - npm install
      - npx update-browserslist-db@latest -y
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - 'demo/dist/**/*'
  name: react-$(date +%Y-%m-%d)