version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Build started on `date`
      - npm install codecov.io coveralls
      - npm run build

  pre_build:
    commands:
      - echo "Pre-build steps..."

  build:
    commands:
      - npm test

  post_build:
    commands:
      - echo Build completed on `date`
      - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
      - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

artifacts:
  files:
    - './dist/**/*'
  name: my-build-artifacts
  discard-paths: yes
  path: path-prefix/