version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Build started on `date`

  pre_build:
    commands:
      - echo "Pre-build steps..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      - nvm install 18.17.1

  build:
    commands:
      - cd demo
      - npm install
      - env
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'